name: Run Hello DevOps Script

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hello-DevOps.sh
        run: bash scripts/hello-DevOps.sh

  greet-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run greet-user.sh (CI test)
        run: |
          echo "admin" | bash scripts/greet-user.sh
